name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [2.7, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Check unicode support
      run: python -c 'import sys; print(sys.maxunicode)'
    - name: Install cryptography
      run: pip install cryptography
    - name: Install pandas
      run: pip install 'pandas==0.24.2'
